### ISSUE TITLE
seems good , But I can not install

### ISSUE THREAD

**Issue by yinflying** [Franco-Poveda/node-cmd-stash#2]
I cant install the script by command:
```
npm install -g command-stash
```
it will show flowing msg and cant continue..
```
[              ] - fetchMetadata: sill  resolveWithNewMoudle  command-stash@1.5.3 checking installable staus
```
Maybe should blame on my network? I dont know . Is there any way install by github rather than npm ?
```
system: manjaro(based on arch)
npm version: 5.3.0
```

**Comment by Franco-Poveda** [comment]
Hi @yinflying thanks for the feedback.

Strange, command-stash should install without problem.

Looks like permissions or network problem. Try:
`sudo npm install -g command-stash
`
Have you installed npm/node with [nvm](https://github.com/creationix/nvm) ? This way you can install global modules with no need of "sudo".
Please post your node -v output.
You can install this module after cloning the repository, (but you have to install the dependencies anyway):
`git clone git@github.com:Franco-Poveda/node-cmd-stash.git && cd ./node-cmd-stash && npm -g install .`

Have you tried yarn? works really good even with network problems. this should work for you:

`
yes | pacman -S yarn && yarn global add command-stash
`


Will be waiting for your results!

**Comment by yinflying** [comment]
thank for your reply! I have affirmed that it is the network problem.... (Because of my country, I need to use 'cnpm'(a npm installer just for my country) to replace 'npm'). 

everything all right ....

**Comment by yinflying** [comment]
Thank you!
I have reinstall the npm (and cnpm) and set the prefix...Here is a solution:
```
$ cd && mkdir npm-install
$ npm config set prefix '/home/xx/npm-install'
$ npm install -g command-stash
```
seems workfine ...

what's more , I find it both create `/root/stash.db` and `~/stash.db` after `sudo stash` , of course it only store the message to `/root/stash.db` ... 

Blame on the way I use the `npm`.... Thank you !
